### ISSUE TITLE
Mac examples aren't OF 0.9-compatible

### ISSUE THREAD

**Issue by asarasua** [asarasua/ofxKinectFeatures#2]
ofxOpenNI doesn't work with OF 0.9, so new examples need to be created for Mac for this OF version.

**Comment by danaavesar** [comment]
Actually I can't get ofxOpenNI to work with anything prior to OF 9.0. The only ofxOpenNI I got working was this version https://github.com/fred-dev/ofxOpenNI. The problem is that ofxKinectFeatures doesn;t seem to be compatible with OF 0.9

**Comment by asarasua** [comment]
Could you tell specifically what problems you are getting with OF 0.9.x?

ofxOpenNI (https://github.com/gameoverhack/ofxOpenNI) works on 0.8.4 (just tested)
ofxKinectFeatures works on 0.9.3 receiving data from osceleton (just tested)

**Comment by asarasua** [comment]
I added a new [example using Synapse ](https://github.com/asarasua/ofxKinectFeatures/tree/master/example-synapse) that works with OF 0.9.3.

I'm not aware of any ofxOpenNI version working in >0.9.0, so for Kinect v1 I think it makes more sense to use other applications (Osceleton, Synapse) to stream the skeleton data.

**Comment by danaavesar** [comment]
This is the error that I am getting in OF 0.9.2 and OF 0.9.3. I am using a Mac and am on Yosemite 10.10.3 and xcode v6.4. 

I built a new project with the project generator and included the addons ofxOpenNI and ofxKinectFeatures. I then copied the src code from the ofxKinectFeatures example. 

<img width="1142" alt="screen shot 2016-04-20 at 8 18 23 am" src="https://cloud.githubusercontent.com/assets/9297457/14674238/3446566a-06d1-11e6-84f4-00de27290e76.png">

**Comment by asarasua** [comment]
Thanks for pointing this out.

This was due to an update I hadn't merged from the develop branch.

If you download/clone ofxKinectFeatures now, with the commit I made before for the example, you shouldn't get this problem.

**Comment by danaavesar** [comment]
Awesome! You are right that version of ofxOpenNI works for OF 8.4, so thats
good to know.

_Dana Avesar_

**Comment by danaavesar** [comment]
I cloned the latest code and am still getting errors. I am getting 91 errors. Again I created a new project in the project generator including the ofxOpenNI and ofxKinectFeatures addons, then I copied the src code from the ofKinectFeatures example that uses ofxOpenNI. 

<img width="1399" alt="screen shot 2016-04-20 at 9 09 51 am" src="https://cloud.githubusercontent.com/assets/9297457/14675636/e459156e-06d7-11e6-8d5f-bd82f292d331.png">

**Comment by asarasua** [comment]
Those errors tell that the methods from OpenNI are not defined for architecture x86_64, which is true (you're building for 64-bit). The OpenNI .dylib files that come with ofxOpenNI are 32-bit.

Again, this is a problem from the external library being used for the skeleton tracking, which is not a problem of ofxKinectFeatures itself. As a guide I would say:
- If you _need_ to integrate the skeleton tracking in the application itself (e.g. because you want to visualize the RGB/RGBD data as well) and you're on Mac, I would use OF 0.8.4 and build 32 bit.
- If you prefer to use OF 0.9.x for whatever reason, then afik there is no working addon for Mac to perform the skeleton tracking, so instead I would use some external software (Osceleton, Synapse) and get the position info via OSC.

**Comment by danaavesar** [comment]
Ok thanks for the help. The interesting thins is that when I run the
ofxOpenNI example by itself on OF 0.9.2 it does work, so I don't know why
it gives problems in the ofxKinectFeatures example.

_Dana Avesar_

**Comment by asarasua** [comment]
Compare the configuration, is the ofxOpenNI example building for 64-bit?

**Comment by danaavesar** [comment]
Yes it is building for 64-bit
 [image: Inline image 1]

_Dana Avesar_

**Comment by asarasua** [comment]
Great! I didn't know [fred-dev's ofxOpenNI version](https://github.com/fred-dev/ofxOpenNI) was working on 0.9.x, great to know :)

So there's no reason why it shouldn't work **as long as you copy the libraries as explained in the readme**:

> Copy the 'bin' folder from 'addons/ofxOpenNI/examples/opeNI-SimpleExamples/' to your project directory (this is to have the correct folder structure and config files for openNI to work).
> Copy the 'lib' folder from 'ofxOpenNI/mac/copy_to_data_openni_path' to the 'bin/data/openni' directory of your project.

This is important; it's not enough to create a project with the project generator including ofxOpenNI. It won't work (regardless of whether ofxKinectFeatures is used).

I committed an [example](https://github.com/asarasua/ofxKinectFeatures/tree/master/example-openni-of093) using that version of ofxOpenNI that works. Again, remember to copy the necessary files. The data folder in your project should look like this:

![image](https://cloud.githubusercontent.com/assets/2278621/14677226/07b6daa8-0711-11e6-8018-5312e1ea0c21.png)

**Comment by danaavesar** [comment]
Thank you for the example! Even after moving the "lib" folder into
bin/data/openni
I was still getting the same errors, so Im not sure what the problem was.
However your example works for me!

_Dana Avesar_

**Comment by danaavesar** [comment]
Hello! Im really sorry to bother you again. I thought that maybe you can
help me by giving me an example of how to use the map function for creating
multiple kinectFeatures for multiple users. In the readme you wrote to use
map<int,ofxKinectFeatures> where keys correspond to a skeleton id.

In my ofApp.h file I declared:
 map<int,ofxKinectFeatures> featExtractors

Now how do I assign values to it so that each featExtractor corresponds
with a different skeleton ID? I tried this, however its not right:

for(int i=0; i< kinect.getNumTrackedUsers(); i++){
        ofxOpenNIUser user = kinect.getTrackedUser(i);
        featExtractors[user.getXnID()].setup(JOINT_HEAD, JOINT_TORSO);
  }
I noticed that when you used it for assigning the joints you had to set it
equal to something.

map<int, ofPoint> joints;

```
       for (int j = 0; j < user.getNumJoints(); j++) {
           joints[j] = user.getJoint((Joint)j).getWorldPosition();
       }
```

Sorry for my ignorance! Ive just been looking it up and struggling to get
it working.

_Dana Avesar_

**Comment by danaavesar** [comment]
HI Alvaro, im still having trouble with setting an ofxKinectFeature
variable for each user being tracked.

I have declared the vector in my header file map<int,ofxKinectFeatures>
featExtractors;

Then I set it up as with keys that point to the userId of the skeleton:[image:
Inline image 1]

I then check to see if a skeleton leaves and remove it from the
featExtractors vector:
[image: Inline image 2]

However when I load in the joints to each featExtractor the program
crashes. In other words when featExtractors[userId].update(joints) is
uncommented and there are more than one skeleton in the program it crashes.
[image: Inline image 3]

How were you thinking of setting it up with multiple featExtractors for
each skeleton?

_Dana Avesar_
